ARG base_image=ghcr.io/openwall/john:latest
FROM ${base_image}
USER root
RUN apt-get update -qq && \
    export DEBIAN_FRONTEND="noninteractive" && \
    apt-get install -y python python3 perl ruby && \
    # Clean the image
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*
USER JtR
