ARG base_image=ghcr.io/openwall/john:latest
FROM ${base_image}
USER root
RUN apt-get update -qq && \
    export DEBIAN_FRONTEND="noninteractive" && \
    apt-get install -y python2-minimal python3-minimal perl-base ruby && \
    # Clean the image
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/* && \
    ln -s python2 /usr/bin/python
USER JtR
