######################################################################
# Copyright (c) 2021 Claudio André <claudioandre.br at gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY; express or implied.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, as expressed in version 2, seen at
# http://www.gnu.org/licenses/gpl-2.0.html
######################################################################
name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Is it a release build (needs a git checkout)?'
        required: true
        default: 'false'
      hash:
        description: 'The commit hash to be used'
        required: false
        default: 'a16c8a76259ab870c07e5123c237b1900402d9a6'
      VERSION:
        description: 'The software version'
        required: true
        default: '1.9.01'  #TODO: edit before release (JUMBO_RELEASE)
      VERSION_NAME:
        description: 'The software version name'
        required: true
        default: '1.9.0-jumbo-1+'  #TODO: edit before release (JUMBO_RELEASE)
      tag:
        description: 'The image tag'
        required: true
        default: 'latest'  #TODO: edit before release (JUMBO_RELEASE)

env:
  REPO: ghcr.io/${{ github.repository_owner }}/john

jobs:
  push_to_registry:
    name: Push Docker image to a registry
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -u)"

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ../../Dockerfile.slim
          build-args: |
            release=${{ github.event.inputs.release }}
            commit=${{ github.event.inputs.hash }}
            BUILD_DATE=${{ steps.date.outputs.date }}
            VERSION=${{ github.event.inputs.VERSION }}
            VERSION_NAME=${{ github.event.inputs.VERSION_NAME }}

          tags: |
            ${{ env.REPO }}:${{ github.event.inputs.tag }}
            ${{ env.REPO }}:${{ github.event.inputs.tag }}-slim
            ${{ env.REPO }}:${{ github.event.inputs.tag }}_J${{ github.run_number }}
            ${{ env.REPO }}:${{ github.event.inputs.tag }}-slim_J${{ github.run_number }}

      - name: Build container image with scripting support
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ../../Dockerfile.scripting
          build-args: |
            base_image=${{ env.REPO }}:${{ github.event.inputs.tag }}-slim
            release=${{ github.event.inputs.release }}
            commit=${{ github.event.inputs.hash }}
            BUILD_DATE=${{ steps.date.outputs.date }}
            VERSION=${{ github.event.inputs.VERSION }}
            VERSION_NAME=${{ github.event.inputs.VERSION_NAME }}

          tags: |
            ${{ env.REPO }}:${{ github.event.inputs.tag }}-full
            ${{ env.REPO }}:${{ github.event.inputs.tag }}-full_J${{ github.run_number }}

